import type { KeepRange, SourceMediaMetadata } from "./fcpxmlV1.js";

export interface AafBridgeManifest {
  schemaVersion: 1;
  generatedAtUtc: string;
  source: SourceMediaMetadata;
  keepRanges: KeepRange[];
  notes: string[];
}

export function buildAafBridgeManifest(
  keepRanges: KeepRange[],
  source: SourceMediaMetadata,
): AafBridgeManifest {
  return {
    schemaVersion: 1,
    generatedAtUtc: new Date().toISOString(),
    source,
    keepRanges: keepRanges
      .filter((r) => r.sourceEndSec > r.sourceStartSec)
      .map((r) => ({
        sourceStartSec: Number(r.sourceStartSec.toFixed(6)),
        sourceEndSec: Number(r.sourceEndSec.toFixed(6)),
        outputStartSec: Number(r.outputStartSec.toFixed(6)),
      })),
    notes: [
      "Generated by Bit Cut Studio AAF bridge.",
      "Use import_aaf.py with OpenTimelineIO + otio-aaf-adapter installed to produce binary .aaf.",
      "Fallback interchange files (.fcpxml/.edl/.xml) are included in the bridge package.",
    ],
  };
}

export function aafBridgeImporterScript(defaultManifestFile = "manifest.json"): string {
  return `#!/usr/bin/env python3
"""
Bit Cut Studio AAF bridge importer

Usage:
  python3 import_aaf.py --manifest manifest.json --out timeline.aaf
"""

from __future__ import annotations

import argparse
import json
import pathlib
import sys


def die(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def load_manifest(path: pathlib.Path) -> dict:
    if not path.exists():
        die(f"Manifest not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def make_timeline(manifest: dict):
    try:
        import opentimelineio as otio
    except Exception as exc:
        die(
            "Missing dependency 'opentimelineio'. Install with: pip install opentimelineio\\n"
            f"Details: {exc}"
        )

    source = manifest.get("source") or {}
    media_path = str(source.get("path") or "")
    fps = float(source.get("fps") or 30.0)

    timeline = otio.schema.Timeline(name="Bit Cut Timeline")
    track = otio.schema.Track(name="V1", kind=otio.schema.TrackKind.Video)

    available = otio.opentime.TimeRange(
        start_time=otio.opentime.RationalTime(0, fps),
        duration=otio.opentime.RationalTime(10**9, fps),
    )

    media_ref = otio.schema.ExternalReference(
        target_url=pathlib.Path(media_path).resolve().as_uri() if media_path else "",
        available_range=available,
    )

    for i, r in enumerate(manifest.get("keepRanges") or []):
        start = float(r["sourceStartSec"])
        end = float(r["sourceEndSec"])
        clip = otio.schema.Clip(name=f"Clip {i+1}")
        clip.media_reference = media_ref
        clip.source_range = otio.opentime.TimeRange(
            start_time=otio.opentime.RationalTime(start * fps, fps),
            duration=otio.opentime.RationalTime((end - start) * fps, fps),
        )
        track.append(clip)

    timeline.tracks.append(track)
    return timeline


def write_aaf(timeline, out_path: pathlib.Path) -> None:
    try:
        import otio_aaf_adapter  # noqa: F401  # required by OTIO adapter registry
    except Exception as exc:
        die(
            "Missing dependency 'otio-aaf-adapter'. Install with: pip install otio-aaf-adapter\\n"
            f"Details: {exc}"
        )

    try:
        import opentimelineio as otio
        otio.adapters.write_to_file(timeline, str(out_path), adapter_name="AAF")
    except Exception as exc:
        die(
            "Failed to write AAF via OpenTimelineIO AAF adapter.\\n"
            "Check adapter/media compatibility and try fallback files in this package.\\n"
            f"Details: {exc}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate binary AAF from Bit Cut manifest")
    parser.add_argument("--manifest", default="${defaultManifestFile}", help="Path to manifest JSON")
    parser.add_argument("--out", default="timeline.aaf", help="Output AAF path")
    parser.add_argument("--validate-only", action="store_true", help="Validate manifest and dependencies only")
    args = parser.parse_args()

    manifest_path = pathlib.Path(args.manifest)
    manifest = load_manifest(manifest_path)

    if int(manifest.get("schemaVersion") or 0) != 1:
        die("Unsupported manifest schemaVersion")

    timeline = make_timeline(manifest)
    if args.validate_only:
        print("Manifest and OTIO timeline build succeeded.")
        return

    out_path = pathlib.Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_aaf(timeline, out_path)
    print(f"Wrote AAF: {out_path}")


if __name__ == "__main__":
    main()
`;
}
